import { IconProp } from "@fortawesome/fontawesome-svg-core";
import {
  faPlus,
  faTachometerAlt,
  faTh,
  faBuilding,
  faUserCircle,
  faGlobe,
  faPen,
  faBriefcase,
  faUser,
  faLock,
  faCog,
  faRocket,
  faShoppingCart,
  faAddressBook,
  faLifeRing,
  faUsers,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faSearch,
  faBell,
  faMoon,
  faMessage,
} from "@fortawesome/free-solid-svg-icons";

export const icons: { [key: string]: IconProp } = {
  "select-project": faPlus,
  "tachometer-alt": faTachometerAlt,
  th: faTh,
  building: faBuilding,
  "user-circle": faUserCircle,
  globe: faGlobe,
  pen: faPen,
  briefcase: faBriefcase,
  user: faUser,
  lock: faLock,
  cog: faCog,
  rocket: faRocket,
  "shopping-cart": faShoppingCart,
  "address-book": faAddressBook,
  "life-ring": faLifeRing,
  users: faUsers,
  "chevron-right": faChevronRight,
  "chevron-down": faChevronDown,
  "chevron-up": faChevronUp,
  search: faSearch,
  bell: faBell,
  moon: faMoon,
  message: faMessage,
};
